//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreWinForms.StoreService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Article", Namespace="http://schemas.datacontract.org/2004/07/StoreService.Models")]
    [System.SerializableAttribute()]
    public partial class Article : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArticleidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Articleid {
            get {
                return this.ArticleidField;
            }
            set {
                if ((this.ArticleidField.Equals(value) != true)) {
                    this.ArticleidField = value;
                    this.RaisePropertyChanged("Articleid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand {
            get {
                return this.BrandField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandField, value) != true)) {
                    this.BrandField = value;
                    this.RaisePropertyChanged("Brand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Information {
            get {
                return this.InformationField;
            }
            set {
                if ((object.ReferenceEquals(this.InformationField, value) != true)) {
                    this.InformationField = value;
                    this.RaisePropertyChanged("Information");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Order", Namespace="http://schemas.datacontract.org/2004/07/StoreService.Models")]
    [System.SerializableAttribute()]
    public partial class Order : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrdedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime OrderDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> ShippingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal TotalPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryType {
            get {
                return this.DeliveryTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryTypeField, value) != true)) {
                    this.DeliveryTypeField = value;
                    this.RaisePropertyChanged("DeliveryType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrdedBy {
            get {
                return this.OrdedByField;
            }
            set {
                if ((object.ReferenceEquals(this.OrdedByField, value) != true)) {
                    this.OrdedByField = value;
                    this.RaisePropertyChanged("OrdedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate {
            get {
                return this.OrderDateField;
            }
            set {
                if ((this.OrderDateField.Equals(value) != true)) {
                    this.OrderDateField = value;
                    this.RaisePropertyChanged("OrderDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderId {
            get {
                return this.OrderIdField;
            }
            set {
                if ((this.OrderIdField.Equals(value) != true)) {
                    this.OrderIdField = value;
                    this.RaisePropertyChanged("OrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentOption {
            get {
                return this.PaymentOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentOptionField, value) != true)) {
                    this.PaymentOptionField = value;
                    this.RaisePropertyChanged("PaymentOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> ShippingDate {
            get {
                return this.ShippingDateField;
            }
            set {
                if ((this.ShippingDateField.Equals(value) != true)) {
                    this.ShippingDateField = value;
                    this.RaisePropertyChanged("ShippingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPrice {
            get {
                return this.TotalPriceField;
            }
            set {
                if ((this.TotalPriceField.Equals(value) != true)) {
                    this.TotalPriceField = value;
                    this.RaisePropertyChanged("TotalPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderItem", Namespace="http://schemas.datacontract.org/2004/07/StoreService.Models")]
    [System.SerializableAttribute()]
    public partial class OrderItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ArticleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int fkOrderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int itemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ArticleId {
            get {
                return this.ArticleIdField;
            }
            set {
                if ((this.ArticleIdField.Equals(value) != true)) {
                    this.ArticleIdField = value;
                    this.RaisePropertyChanged("ArticleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fkOrderId {
            get {
                return this.fkOrderIdField;
            }
            set {
                if ((this.fkOrderIdField.Equals(value) != true)) {
                    this.fkOrderIdField = value;
                    this.RaisePropertyChanged("fkOrderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int itemId {
            get {
                return this.itemIdField;
            }
            set {
                if ((this.itemIdField.Equals(value) != true)) {
                    this.itemIdField = value;
                    this.RaisePropertyChanged("itemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/StoreService.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NationalIdentificationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneCellField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneHomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalIdentificationNumber {
            get {
                return this.NationalIdentificationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NationalIdentificationNumberField, value) != true)) {
                    this.NationalIdentificationNumberField = value;
                    this.RaisePropertyChanged("NationalIdentificationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneCell {
            get {
                return this.PhoneCellField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneCellField, value) != true)) {
                    this.PhoneCellField = value;
                    this.RaisePropertyChanged("PhoneCell");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneHome {
            get {
                return this.PhoneHomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneHomeField, value) != true)) {
                    this.PhoneHomeField = value;
                    this.RaisePropertyChanged("PhoneHome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipCodeField, value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StoreService.IStoreService")]
    public interface IStoreService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnArticleById", ReplyAction="http://tempuri.org/IStoreService/ReturnArticleByIdResponse")]
        StoreWinForms.StoreService.Article ReturnArticleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnArticleById", ReplyAction="http://tempuri.org/IStoreService/ReturnArticleByIdResponse")]
        System.Threading.Tasks.Task<StoreWinForms.StoreService.Article> ReturnArticleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllArticles", ReplyAction="http://tempuri.org/IStoreService/ReturnAllArticlesResponse")]
        System.Collections.Generic.List<StoreWinForms.StoreService.Article> ReturnAllArticles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllArticles", ReplyAction="http://tempuri.org/IStoreService/ReturnAllArticlesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.Article>> ReturnAllArticlesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddOrUpdateArticle", ReplyAction="http://tempuri.org/IStoreService/AddOrUpdateArticleResponse")]
        void AddOrUpdateArticle(StoreWinForms.StoreService.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddOrUpdateArticle", ReplyAction="http://tempuri.org/IStoreService/AddOrUpdateArticleResponse")]
        System.Threading.Tasks.Task AddOrUpdateArticleAsync(StoreWinForms.StoreService.Article article);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddOrUpdateOrder", ReplyAction="http://tempuri.org/IStoreService/AddOrUpdateOrderResponse")]
        void AddOrUpdateOrder(StoreWinForms.StoreService.Order order, System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem> orderlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddOrUpdateOrder", ReplyAction="http://tempuri.org/IStoreService/AddOrUpdateOrderResponse")]
        System.Threading.Tasks.Task AddOrUpdateOrderAsync(StoreWinForms.StoreService.Order order, System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem> orderlist);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/SearchOrderById", ReplyAction="http://tempuri.org/IStoreService/SearchOrderByIdResponse")]
        StoreWinForms.StoreService.Order SearchOrderById(int orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/SearchOrderById", ReplyAction="http://tempuri.org/IStoreService/SearchOrderByIdResponse")]
        System.Threading.Tasks.Task<StoreWinForms.StoreService.Order> SearchOrderByIdAsync(int orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllOrderItemsByfkKey", ReplyAction="http://tempuri.org/IStoreService/ReturnAllOrderItemsByfkKeyResponse")]
        System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem> ReturnAllOrderItemsByfkKey(int fkOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllOrderItemsByfkKey", ReplyAction="http://tempuri.org/IStoreService/ReturnAllOrderItemsByfkKeyResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem>> ReturnAllOrderItemsByfkKeyAsync(int fkOrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/RemoveOrderById", ReplyAction="http://tempuri.org/IStoreService/RemoveOrderByIdResponse")]
        void RemoveOrderById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/RemoveOrderById", ReplyAction="http://tempuri.org/IStoreService/RemoveOrderByIdResponse")]
        System.Threading.Tasks.Task RemoveOrderByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/RemoveArticleById", ReplyAction="http://tempuri.org/IStoreService/RemoveArticleByIdResponse")]
        void RemoveArticleById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/RemoveArticleById", ReplyAction="http://tempuri.org/IStoreService/RemoveArticleByIdResponse")]
        System.Threading.Tasks.Task RemoveArticleByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllActiveOrders", ReplyAction="http://tempuri.org/IStoreService/ReturnAllActiveOrdersResponse")]
        System.Collections.Generic.List<StoreWinForms.StoreService.Order> ReturnAllActiveOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllActiveOrders", ReplyAction="http://tempuri.org/IStoreService/ReturnAllActiveOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.Order>> ReturnAllActiveOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllSentOrders", ReplyAction="http://tempuri.org/IStoreService/ReturnAllSentOrdersResponse")]
        System.Collections.Generic.List<StoreWinForms.StoreService.Order> ReturnAllSentOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllSentOrders", ReplyAction="http://tempuri.org/IStoreService/ReturnAllSentOrdersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.Order>> ReturnAllSentOrdersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/UpdateOrderToSent", ReplyAction="http://tempuri.org/IStoreService/UpdateOrderToSentResponse")]
        void UpdateOrderToSent(StoreWinForms.StoreService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/UpdateOrderToSent", ReplyAction="http://tempuri.org/IStoreService/UpdateOrderToSentResponse")]
        System.Threading.Tasks.Task UpdateOrderToSentAsync(StoreWinForms.StoreService.Order order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllUsers", ReplyAction="http://tempuri.org/IStoreService/ReturnAllUsersResponse")]
        System.Collections.Generic.List<StoreWinForms.StoreService.User> ReturnAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/ReturnAllUsers", ReplyAction="http://tempuri.org/IStoreService/ReturnAllUsersResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.User>> ReturnAllUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IStoreService/AddOrUpdateUserResponse")]
        void AddOrUpdateUser(StoreWinForms.StoreService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IStoreService/AddOrUpdateUserResponse")]
        System.Threading.Tasks.Task AddOrUpdateUserAsync(StoreWinForms.StoreService.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/RemoveUserById", ReplyAction="http://tempuri.org/IStoreService/RemoveUserByIdResponse")]
        void RemoveUserById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStoreService/RemoveUserById", ReplyAction="http://tempuri.org/IStoreService/RemoveUserByIdResponse")]
        System.Threading.Tasks.Task RemoveUserByIdAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStoreServiceChannel : StoreWinForms.StoreService.IStoreService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StoreServiceClient : System.ServiceModel.ClientBase<StoreWinForms.StoreService.IStoreService>, StoreWinForms.StoreService.IStoreService {
        
        public StoreServiceClient() {
        }
        
        public StoreServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StoreServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StoreWinForms.StoreService.Article ReturnArticleById(int id) {
            return base.Channel.ReturnArticleById(id);
        }
        
        public System.Threading.Tasks.Task<StoreWinForms.StoreService.Article> ReturnArticleByIdAsync(int id) {
            return base.Channel.ReturnArticleByIdAsync(id);
        }
        
        public System.Collections.Generic.List<StoreWinForms.StoreService.Article> ReturnAllArticles() {
            return base.Channel.ReturnAllArticles();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.Article>> ReturnAllArticlesAsync() {
            return base.Channel.ReturnAllArticlesAsync();
        }
        
        public void AddOrUpdateArticle(StoreWinForms.StoreService.Article article) {
            base.Channel.AddOrUpdateArticle(article);
        }
        
        public System.Threading.Tasks.Task AddOrUpdateArticleAsync(StoreWinForms.StoreService.Article article) {
            return base.Channel.AddOrUpdateArticleAsync(article);
        }
        
        public void AddOrUpdateOrder(StoreWinForms.StoreService.Order order, System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem> orderlist) {
            base.Channel.AddOrUpdateOrder(order, orderlist);
        }
        
        public System.Threading.Tasks.Task AddOrUpdateOrderAsync(StoreWinForms.StoreService.Order order, System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem> orderlist) {
            return base.Channel.AddOrUpdateOrderAsync(order, orderlist);
        }
        
        public StoreWinForms.StoreService.Order SearchOrderById(int orderid) {
            return base.Channel.SearchOrderById(orderid);
        }
        
        public System.Threading.Tasks.Task<StoreWinForms.StoreService.Order> SearchOrderByIdAsync(int orderid) {
            return base.Channel.SearchOrderByIdAsync(orderid);
        }
        
        public System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem> ReturnAllOrderItemsByfkKey(int fkOrderId) {
            return base.Channel.ReturnAllOrderItemsByfkKey(fkOrderId);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.OrderItem>> ReturnAllOrderItemsByfkKeyAsync(int fkOrderId) {
            return base.Channel.ReturnAllOrderItemsByfkKeyAsync(fkOrderId);
        }
        
        public void RemoveOrderById(int id) {
            base.Channel.RemoveOrderById(id);
        }
        
        public System.Threading.Tasks.Task RemoveOrderByIdAsync(int id) {
            return base.Channel.RemoveOrderByIdAsync(id);
        }
        
        public void RemoveArticleById(int id) {
            base.Channel.RemoveArticleById(id);
        }
        
        public System.Threading.Tasks.Task RemoveArticleByIdAsync(int id) {
            return base.Channel.RemoveArticleByIdAsync(id);
        }
        
        public System.Collections.Generic.List<StoreWinForms.StoreService.Order> ReturnAllActiveOrders() {
            return base.Channel.ReturnAllActiveOrders();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.Order>> ReturnAllActiveOrdersAsync() {
            return base.Channel.ReturnAllActiveOrdersAsync();
        }
        
        public System.Collections.Generic.List<StoreWinForms.StoreService.Order> ReturnAllSentOrders() {
            return base.Channel.ReturnAllSentOrders();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.Order>> ReturnAllSentOrdersAsync() {
            return base.Channel.ReturnAllSentOrdersAsync();
        }
        
        public void UpdateOrderToSent(StoreWinForms.StoreService.Order order) {
            base.Channel.UpdateOrderToSent(order);
        }
        
        public System.Threading.Tasks.Task UpdateOrderToSentAsync(StoreWinForms.StoreService.Order order) {
            return base.Channel.UpdateOrderToSentAsync(order);
        }
        
        public System.Collections.Generic.List<StoreWinForms.StoreService.User> ReturnAllUsers() {
            return base.Channel.ReturnAllUsers();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<StoreWinForms.StoreService.User>> ReturnAllUsersAsync() {
            return base.Channel.ReturnAllUsersAsync();
        }
        
        public void AddOrUpdateUser(StoreWinForms.StoreService.User user) {
            base.Channel.AddOrUpdateUser(user);
        }
        
        public System.Threading.Tasks.Task AddOrUpdateUserAsync(StoreWinForms.StoreService.User user) {
            return base.Channel.AddOrUpdateUserAsync(user);
        }
        
        public void RemoveUserById(int id) {
            base.Channel.RemoveUserById(id);
        }
        
        public System.Threading.Tasks.Task RemoveUserByIdAsync(int id) {
            return base.Channel.RemoveUserByIdAsync(id);
        }
    }
}
